# This file defines all the services for your project on Render.
# Render will automatically create and deploy everything when you push this to your Git repo.

databases:
  - name: urjanet-db
    databaseName: urjanet_db
    plan: free
    region: ohio

services:
  # 1. The Backend FastAPI API
  - type: web
    name: urjanet-api
    env: docker
    repo: https://github.com/Nikunj2608/Smart-EMS-.git
    branch: main
    rootDir: ./services/api
    dockerfilePath: ./services/api/Dockerfile
    plan: free
    region: ohio
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urjanet-db
          property: internalConnectionString
      - key: INFLUXDB_URL
        sync: false
      - key: INFLUXDB_TOKEN
        sync: false
      - key: INFLUXDB_ORG
        sync: false
      - key: INFLUXDB_BUCKET
        sync: false
      - key: MQTT_BROKER_HOST
        sync: false
      - key: MQTT_BROKER_PORT
        sync: false
      - key: MQTT_TOPIC
        sync: false
      - key: URJANET_API_TOKEN
        sync: false

  # 2. The Ingestion Service
  - type: worker
    name: urjanet-ingestion
    env: docker
    repo: https://github.com/Nikunj2608/Smart-EMS-.git
    branch: main
    rootDir: ./services/ingestion
    dockerfilePath: ./services/ingestion/Dockerfile
    plan: free
    region: ohio
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urjanet-db
          property: internalConnectionString
      - key: INFLUXDB_URL
        sync: false
      - key: INFLUXDB_TOKEN
        sync: false
      - key: INFLUXDB_ORG
        sync: false
      - key: INFLUXDB_BUCKET
        sync: false
      - key: MQTT_BROKER_HOST
        sync: false
      - key: MQTT_BROKER_PORT
        sync: false
      - key: MQTT_TOPIC
        sync: false

  # 3. The React Frontend
  - type: web
    name: urjanet-frontend
    env: static
    repo: https://github.com/Nikunj2608/Smart-EMS-.git
    branch: main
    rootDir: ./frontend
    plan: free
    region: ohio
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: urjanet-api
          property: url

  # 5. The Scheduled Job (Fixed)
  - type: cron
    name: adaptive-scheduler
    env: shell
    region: ohio
    schedule: "0 * * * *"
    plan: free
    startCommand: curl -f -H "Authorization: Bearer ${URJANET_API_TOKEN}" "${RENDER_EXTERNAL_URL}/api/system/recommendation"
    envVars:
      - key: URJANET_API_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: urjanet-api
          property: url

